#!/usr/bin/bash


# As yourself...
#---------------------------------------------------------------------

alias tfv="terraform validate -check-variables=false"
alias tfc="terraform validate -check-variable=false && terraform fmt"
export EDITOR="vim"
export TERRAGRUNT_DEFAULT_MODULES_REPO=/home/ejtravis/cloudfirst/as-aws-modules
terragrunt-source(){
    TERRAGRUNT_SOURCE=$($(which terragrunt-source)) terragrunt $@
}
alias tgs=terragrunt-source
alias python="python3.6"
alias pip="pip3.6"

add_to_path "/home/ejtravis/.local/shared"
add_to_path "/home/ejtravis/.local/bin"
export DOCKER_HOST="tcp://0.0.0.0:2375"
export PAGER=less
