#!/usr/bin/bash
[ -z "$PS1" ] && return

SOURCERY_PROFILE="${HOME}/.sourcery/sources/profile.bash"
echo ${SOURCERY_PROFILE}
if [ -e ${SOURCERY_PROFILE} ]; then
    source ${SOURCERY_PROFILE}
else
    echo -e "Bash profile template error.\n"
fi
