# 1. If you haven't already:
# 	 Run 'Makefile' located in this directory
# 2. Log in as su user on the system
# 3. Copy this file into the su-user's home directory
# 4. Run
#
# This makefile is designed to automate the testing of an RPM
# within the context of an SDG virtual environment.
#
# This makefile should be placed in the home directory of the su-user.
SHELL=/bin/bash
#####################################################################
# Variable(s) that will definitely need to change.
#####################################################################
USR=ejtravis
SRC=/home/$(USR)/CompassSpaceRequest/
PACKAGE=IC2gCorrelation
VERSION=4.1b1
WSGI=$(PACKAGE)/config/wsgi.conf.template
#####################################################################
# Variable(s) that 'might' need to change.
#####################################################################
HOME=/services/$(SVC)/
DST=$(HOME)rpms/
#####################################################################
# Variables that in all likelihood will not need to change.
#####################################################################
SVC=$(shell whoami)
RPM=$(PACKAGE)-$(VERSION)-1.el6.noarch.rpm
SUDO=sudo /sbin/service
SHIB=$(SUDO) shibd
HTTPD=$(SUDO) httpd
RPM_INFO=$(HOME)$(PACKAGE).info
RPM_CONTENTS=$(HOME)$(PACKAGE).contents

all: clean.o setup.o uninstall.o install.o config.o restart.o done.o

clean.o:
	@echo 'cleaning...'
	rm -rf $(PACKAGE)
	rm -rf $(DST)
	rm -rf $(HOME)public_html
	touch $(RPM_INFO)
	touch $(RPM_CONTENTS)
	rm $(RPM_INFO)
	rm $(RPM_CONTENTS)

setup.o:
	@echo 'setting up installation environment...'
	mkdir -p $(HOME)public_html/http
	mkdir -p $(HOME)public_html/https
	mkdir $(DST)
	cp $(SRC)$(RPM) $(DST)
	sdg_sync

uninstall.o:
	@echo 'uninstalling old package version...'
	rpm --query --info --package $(DST)$(RPM) >> $(RPM_INFO)
	rpm --query --list --package $(DST)$(RPM) >> $(RPM_CONTENTS)
	rpm --erase $(PACKAGE)

install.o: uninstall.o
	@echo 'installing new package version...'
	rpm --upgrade $(DST)$(RPM)

config.o: install.o
	@echo 'installing config files into package...'
	mv $(WSGI) apache/wsgi.conf
	cp TempConfig/* $(PACKAGE)/config

restart.o:
	@echo 'restarting services...'
	@echo '    shibboleth'
	$(SHIB) stop
	$(SHIB) start
	@echo '    Httpd'
	$(HTTPD) stop
	$(HTTPD) start

done.o:
	@echo '---------->DONE'
