#!/usr/bin/bash
#####################################################################
# Functions
#####################################################################

#######################################
# Extract the contents of an RPM without installing it.
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   None
########################################
xtractRPM(){
    rpm2cpio  | cpio -idmv
}


#####################################################################
# Aliases
#####################################################################

alias cdsource="cd $SOURCERY"
alias extractRPM=xtractRPM
alias sourcery.clean="sourcery.bash --clean;sourcery"
alias sourcery.init="sourcery;sourcery.bash --initialize;sourcery"
alias sourcery.reset="sourcery.bash --reset;sourcery"
alias vi="vim"
