#!/usr/bin/bash

echo -e "\t${SOURCERY_USR_DIR}/bashrc"

umask 022

#####################################################################
# Environment Variables
#####################################################################
LS_COLORS='di=96:ln=35;100'
add_to_path ${HOME}/twee

export SOURCERY_BASHINIT=${SOURCERY_BASHLIB}/init
export SOURCERY_PYINIT=${SOURCERY_PYLIB}/init

add_to_path ${SOURCERY_BASHINIT}
add_to_path /cygdrive/c/HashiCorp/Vagrant/bin
add_to_pythonpath ${SOURCERY_PYINIT}

#====================================================================
# Git Aware Prompt
#--------------------------------------------------------------------
export GITAWAREPROMPT=${SOURCERY_SOURCES}/utils/git-aware-prompt
source $GITAWAREPROMPT/main.sh
export PS1="\n\[$txtgrn\]\u\[$txtred\]@\[$txtgrn\]\h\n\$git_branch\[$txtred\]\$git_dirty\[$txtylw\]pwd: \w\n\[$txtrst\]\$ "
#====================================================================


#====================================================================
# X-Forwarding Automation
#   - Allow service user to access X-forwarding options.
#--------------------------------------------------------------------

if [ -e ~/.Xauthority ]; then
    chmod 644 ~/.Xauthority
fi

#--------------------------------------------------------------------
