#!/usr/bin/bash

#####################################################################
# Aliases
#####################################################################

alias startshib="${SOURCERY_SUDO} shibd start"
alias startweb="${SOURCRY_SUDO} httpd start"
alias stopshib="${SOURCERY_SUDO} shibd stop"
alias stopweb="${SOURCERY_SUDO} httpd stop"

alias vim="vim -u ${VIMRC}"
alias vi="vim"

