#!/usr/bin/bash

#####################################################################
# Aliases
#####################################################################

alias startshib="${SUDO} shibd start"
alias startweb="${SUDO} httpd start"
alias stopshib="${SUDO} shibd stop"
alias stopweb="${SUDO} httpd stop"

alias vim="vim -u ${VIMRC}"
alias vi="vim"

