#!/usr/bin/bash

echo -e "\t${SU}/bashrc"

#####################################################################
# Temporary Variables
#####################################################################
LS_COLORS="di=93"
SUDO="sudo /sbin/service"

export PS1="\n\u@\h\npwd: \w\n$ "
