#!/usr/bin/bash

echo -e "\t${SOURCERY_SU_DIR}/bashrc"

#####################################################################
# Temporary Variables
#####################################################################
LS_COLORS="di=93"
SOURCERY_SUDO="sudo /sbin/service"

export PS1="\n\u@\h\npwd: \w\n$ "

