#!/usr/bin/bash

gitPullWorkspace(){
    find . -maxdepth 1 -mindepth 1 -type d -exec git --git-dir={}/.git --work-tree=$PWD/{} pull \;
}



alias c="clear"
alias clearall="clear && printf '\033[3J'" # Clear terminal scroll buffer
alias collections="scl enable python27 sdg_2015a_python27 zsh"
alias djtest="python manage.py test"
alias env="env | sort"
alias GPW="gitPullWorkspace"
alias ls="ls --group-directories-first --color=auto"
alias sourcery="source ${SOURCERY_MYHOME}/.bash_profile"
