#!/usr/bin/bash
echo "        ${SOURCERY_SOURCES}/all/aliases"


gitPullWorkspace(){
    find . -maxdepth 1 -mindepth 1 -type d -exec git --git-dir={}/.git --work-tree=$PWD/{} pull \;
}

gitCleanWorkspace(){
    find . -maxdepth 1 -mindepth 1 -type d -exec git --git-dir={}/.git --work-tree=$PWD/{} gc \;
}


alias c="clear"
alias clearall="clear && printf '\033[3J'" # Clear terminal scroll buffer
alias collections="scl enable python27 sdg_2015a_python27 zsh"
alias env="env | sort"
alias GPW="gitPullWorkspace"
alias GCW="gitCleanWorkspace"
alias ls="ls --group-directories-first --color=auto"
alias sourcery="source ${SOURCERY_MYHOME}/.bash_profile"
