#!/usr/bin/bash
echo "        ${SOURCERY_SOURCES}/all/aliases"


gitPullWorkspace(){
    find . -maxdepth 1 -mindepth 1 -type d -exec git --git-dir={}/.git --work-tree=$PWD/{} pull \;
}

gitCleanWorkspace(){
    find . -maxdepth 1 -mindepth 1 -type d -exec git --git-dir={}/.git --work-tree=$PWD/{} gc \;
}


alias c="clear && ls"
alias clearall="clear && printf '\033[3J'" # Clear terminal scroll buffer
alias collections="scl enable python27 sdg_2015a_python27 zsh"
alias dockerc="docker-compose"
alias env="env | sort"
alias gpw="gitPullWorkspace"
alias gcw="gitCleanWorkspace"
alias kc="kubectl"
alias ls="ls --group-directories-first --color=auto -p"
alias sourcery="source ${SOURCERY_MYHOME}/.bash_profile"
alias sshhosts="sed -rn 's/^\s*Host\s+(.*)\s*/\1/ip' ~/.ssh/config"
alias tg="terragrunt"
alias tf="terraform"

[ -z $PS1 ] && return 0

function cd {
    builtin cd "$@" && ls -F
}
