#!/usr/bin/bash

echo -e "\t${SOURCES}/all/bashrc"
#####################################################################
# Environment Variables
#####################################################################

export EDITOR=vim
export LS_COLORS=''
export MYLIBS=${SOURCERY}/mylibs
export MYPYLIB=${MYLIBS}/pylib
export MYBASHLIB=${MYLIBS}/bashlib
export PYTHONSTARTUP=${MYPYLIB}/pythonstartup.py
export VIMRC=${MYHOME}/.vimrc
export PYLINTRC=${MYHOME}/.pylintrc
# FIXME
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.51-1.b16.el6_7.x86_64/jre

add_to_path ${SOURCERY}
add_to_path ${MYBASHLIB}
add_to_pythonpath ~/central-registry-unit-test/module/
add_to_pythonpath ${MYPYLIB}
if [ -d "${SDIR}" ]; then
    export SERVICE=$(python ${MYPYLIB}/get_service.py)
    add_to_pythonpath /services/${SERVICE}/share/python/django
    # Check for /usr/local/sdg symlink to /services/<service>/sdg
    if [ -d "${SDG}" ]; then
        add_to_path ${SDG}/share/python/django/bin
    
        add_to_pythonpath ${SDG}/share/python/django
        add_to_pythonpath ${SDG}/share/python
    else
        # Add /services/<service>/sdg to paths if symlink not found
        add_error "${SDG} symlink not detected."
        if [ -d "${SDIR}/${SERVICE}" ]; then
            add_to_path ${SDIR}/${SERVICE}/sdg/share/python/django/bin
        
            add_to_pythonpath ${SDIR}/${SERVICE}/sdg/share/python/django
            add_to_pythonpath ${SDIR}/${SERVICE}/sdg/share/python
        else
            add_error "No su entry for ${HOST}. See ${MYPYLIB}/get_service.py"
        fi
    fi
fi

add_to_pythonpath /usr/lib/python2.7/site-packages
add_to_pythonpath /usr/lib64/python2.7/site-packages
add_to_pythonpath /usr/lib/python2.6/site-packages
add_to_pythonpath /usr/lib64/python2.6/site-packages
add_to_pythonpath ${MYHOME}/classNotes/bin/python

